### ISSUE TITLE
Can't run tests with coverage

### ISSUE THREAD

**Issue by dmitry-dedukhin** [r3b/grunt-protractor-coverage#1]
Hi.

I've just installed your module and tried to run tests with coverage.
But I've got the following error:

```
> grunt protractor_coverage
Running "protractor_coverage:files" (protractor_coverage) task
Warning: Unable to read "resources/saveCoverage.tmpl" file (Error code: ENOENT). Use --force to continue.
```

From the source I can see that it tries to open file "resources/saveCoverage.tmpl" using relative path:

``` javascript
var saveCoverageSource = grunt.file.read("resources/saveCoverage.tmpl");
```

Could you please help me with this issue?

**Comment by GopalRaoP** [comment]
Hi,

I am trying to run protractor coverage but i have got errors


D:\grunt-protractor-coverage>grunt test
Running "clean:tests" (clean) task
>> 1 path cleaned.

Running "copy:instrument" (copy) task
Warning: Unable to write "instrumented/resources/app/angularjs" file (Error code
: EISDIR). Use --force to continue.

Aborted due to warnings.

Please help me to get out of this issue.

Thanks&Regards,
P.Gopala Rao.

**Comment by rohitsakala** [comment]
@dmitry-dedukhin Through makeReport, I am getting a json file. But jenkins only accepts xml format of cobertua. How to did you use it Jenkins ??

Any help appreciated.
